name: Check for Duplicate check_uri
on: [pull_request]

jobs:
  duplicate-url-checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Check for duplicate in new JSON
        run: if [ $(grep "uri_check" wmn-data.json | cut -f4 -d'"' | grep -v "replit.com" | uniq -D | head -1) ]; then echo "Found duplicate in wmn-data.json!"; exit 1; else echo "No duplicates found"; fi
        shell: bash
